AWSTemplateFormatVersion: '2010-09-09'
Description: 'Booking Module Lambda and SQS Cloudformation.'

Parameters:
  LabRoleARN:
    Default: arn:aws:iam::626446205647:role/LabRole
    Description: Lab role arn
    Type: String

Resources:
  RequestPackageLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.11
        - python3.12
      Content:
        S3Bucket: my-bucket-us-west-2-123456789012
        S3Key: layer.zip
      Description: Requests Package layer
      LayerName: requestspackage


  GenerateBookingRef:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GenerateBookingRefUsingCF
      Runtime: python3.12
      Role: !Ref LabRoleARN
      Handler: index.handler
      Timeout: 600
      Code:
        S3Bucket: dal-vacation-home
        S3Key:  GenerateBookingRefCode.zip
      Description: Generate Booking Reference lambda function.
      Layers:
        - Ref: 'RequestPackageLayer'
      
  AssignRandomAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AssignRandomAgentUsingCF
      Runtime: python3.12
      Role: !Ref LabRoleARN
      Handler: index.handler
      Timeout: 600
      Code:
        S3Bucket: dal-vacation-home
        S3Key:  AssignRandomAgent.zip
      Description: Assign Random Agent lambda function.
      Layers:
        - Ref: 'RequestPackageLayer'
    
  BookingApproval:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BookingApprovalUsingCF
      Runtime: python3.12
      Role: !Ref LabRoleARN
      Handler: index.handler
      Timeout: 600
      Code:
        S3Bucket: dal-vacation-home
        S3Key:  BookingApproval.zip
      Description: Booking Approval lambda function.
      Layers:
        - Ref: 'RequestPackageLayer'
  
  BookingProcess:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'BookingProcessUsingCF'

  ApproveBookingResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt BookingProcess.RootResourceId
      PathPart: 'approvebooking'
      RestApiId: !Ref BookingProcess

  BookingRoomResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt BookingProcess.RootResourceId
      PathPart: 'approvebooking'
      RestApiId: !Ref BookingProcess
  
  ApproveBookingMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      RestApiId: !Ref BookingProcess
      ResourceId: !GetAtt BookingProcess.RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub
            - arn:aws:apigateway:${AWS::Region}:lambda:path/.../functions/${lambdaArn}/invocations
            - lambdaArn: !GetAtt GenerateBookingRef.Arn

  BookingRoomMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      RestApiId: !Ref BookingProcess
      ResourceId: !GetAtt BookingProcess.RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub
            - arn:aws:apigateway:${AWS::Region}:lambda:path/.../functions/${lambdaArn}/invocations
            - lambdaArn: !GetAtt ApproveBooking.Arn

  ApiGatewayDeployment:
    DependsOn: ApiGatewayMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref BookingProcess
      StageName: prod

  GenerateBookingRefLambdaApiGatewayInvoke:
        Type: AWS::Lambda::Permission
        Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt GenerateBookingRef.Arn
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub arn:aws:execute-api:us-east-1:626446205647:${BookingProcess}/*/POST/bookingRoom

  AssignRandomAgentLambdaApiGatewayInvoke:
        Type: AWS::Lambda::Permission
        Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt ApproveBooking.Arn
        Principal: apigateway.amazonaws.com
        SourceArn: !Sub arn:aws:execute-api:us-east-1:626446205647:${BookingProcess}/*/POST/approveBooking

